# Generated by Django 5.2.4 on 2025-08-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
